# Generated by Django 3.2.16 on 2022-10-17 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=150)),
                ('company_website', models.CharField(blank=True, max_length=200)),
                ('lead_contact', models.ManyToManyField(related_name='lead_contact', to='people.Person')),
            ],
            options={
                'verbose_name': 'Performing Company',
                'verbose_name_plural': 'Performing Companies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('A+', 'Amazing'), ('A', 'Bit fine actually')], default='A', max_length=30)),
                ('subject', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('M', 'Moral'), ('T', 'Technical'), ('A', 'Artistic'), ('N', 'Note')], default='N', max_length=10)),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('APP', 'Applied'), ('COM', 'Complete')], default='APP', max_length=30)),
                ('level', models.CharField(choices=[('PRO', 'Professional'), ('EME', 'Emerging Professional'), ('SEM', 'Semi-Professional'), ('AMA', 'Amateur')], default='PRO', max_length=30)),
                ('outline', models.TextField(blank=True)),
                ('motivation', models.TextField(blank=True)),
                ('funding', models.TextField(blank=True)),
                ('set_outline', models.TextField(blank=True)),
                ('tech_outline', models.TextField(blank=True)),
                ('cast_size', models.IntegerField(default=0)),
                ('crew_size', models.IntegerField(default=0)),
                ('show_duration', models.DurationField(default=0)),
                ('get_in_dur', models.DurationField(default=0)),
                ('get_out_dur', models.DurationField(default=0)),
                ('has_preview', models.BooleanField(default=False)),
                ('notes_general', models.TextField(blank=True)),
                ('via_link', models.CharField(blank=True, max_length=200)),
                ('comments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.comment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programming.company')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programming.event')),
                ('lead_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person')),
                ('slot_preferences', models.ManyToManyField(to='programming.Slot')),
                ('votes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.vote')),
            ],
        ),
    ]
