# Generated by Django 3.2.16 on 2022-10-18 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.comment'),
        ),
        migrations.AlterField(
            model_name='show',
            name='slot_preferences',
            field=models.ManyToManyField(blank=True, null=True, to='programming.Slot'),
        ),
        migrations.AlterField(
            model_name='show',
            name='votes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.vote'),
        ),
    ]
