# Generated by Django 3.2.16 on 2022-10-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_auto_20221018_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='slot_preferences',
            field=models.ManyToManyField(blank=True, to='programming.Slot'),
        ),
    ]
