# Generated by Django 3.2.16 on 2022-10-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_rename_contactdetails_contactdetail'),
        ('programming', '0003_alter_show_slot_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='lead_contact',
        ),
        migrations.AddField(
            model_name='company',
            name='lead_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contact', to='people.person'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
