# Generated by Django 3.2.16 on 2022-10-18 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_auto_20221018_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The short name, eg A1', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='The long name, eg The Sanctuary', max_length=100)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='slot_preferences',
        ),
        migrations.AddField(
            model_name='event',
            name='week_0_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='week_1_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='week_2_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='week_3_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='week_4_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='box_office',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='programming.event'),
        ),
        migrations.AddField(
            model_name='slot',
            name='show',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show'),
        ),
        migrations.AddField(
            model_name='slot',
            name='show_end_time',
            field=models.TimeField(help_text='SHOW, not slot, end time', null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='show_start_time',
            field=models.TimeField(help_text='SHOW, not slot, start time', null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_guarantee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.venue'),
        ),
    ]
