# Generated by Django 3.2.16 on 2022-10-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0006_auto_20221018_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='week_0_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='week_1_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='week_2_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='week_3_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='week_4_start',
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('W0', 'Week 0 Start'), ('W1', 'Week 1 Start'), ('W2', 'Week 2 Start'), ('W3', 'Week 3 Start'), ('W4', 'Week 4 Start')], max_length=50, unique=True)),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.event')),
            ],
        ),
    ]
