# Generated by Django 3.2.16 on 2022-10-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0007_auto_20221018_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_preference',
            field=models.PositiveSmallIntegerField(default=1, unique=True),
        ),
    ]
