# Generated by Django 3.2.16 on 2022-10-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0008_slot_slot_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='event',
        ),
        migrations.AlterField(
            model_name='show',
            name='via_link',
            field=models.CharField(blank=True, max_length=200, verbose_name='VIA Box Office Link'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show'),
        ),
    ]
