# Generated by Django 3.2.16 on 2022-10-18 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0010_venue_parent_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='parent_venue',
            field=models.CharField(choices=[('AUG', 'Paradise in Augustines'), ('VAU', 'Paradise in The Vault')], default='AUG', max_length=30),
        ),
    ]
