# Generated by Django 3.2.16 on 2022-10-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0011_alter_venue_parent_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
