# Generated by Django 3.2.16 on 2022-10-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0012_show_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='has_preview',
        ),
        migrations.AddField(
            model_name='slot',
            name='has_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='week',
            name='offers_preview',
            field=models.BooleanField(default=False),
        ),
    ]
