# Generated by Django 3.2.16 on 2022-10-18 22:57

from django.db import migrations, models
import django.db.models.deletion
import programming.models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0013_auto_20221018_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.week'),
        ),
    ]
