# Generated by Django 3.2.16 on 2022-10-18 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0014_slot_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.week'),
        ),
    ]
