# Generated by Django 3.2.16 on 2022-10-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0015_alter_slot_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['show', 'slot_preference']},
        ),
    ]
