# Generated by Django 3.2.16 on 2022-10-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0017_slot_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accepting_submissions',
            field=models.BooleanField(default=True, help_text='Accepting submissions for show registration'),
        ),
    ]
