# Generated by Django 3.2.16 on 2022-10-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0019_auto_20221019_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='copy_long',
            field=models.TextField(blank=True, help_text='Around 100 words', verbose_name='Marketing copy (long)'),
        ),
        migrations.AlterField(
            model_name='show',
            name='copy_short',
            field=models.TextField(blank=True, help_text='Around 50 words', verbose_name='Marketing copy (short)'),
        ),
    ]
