# Generated by Django 3.2.16 on 2022-10-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0020_auto_20221019_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='show',
            name='votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show'),
        ),
        migrations.AddField(
            model_name='vote',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show'),
        ),
    ]
