# Generated by Django 3.2.16 on 2022-10-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0021_auto_20221019_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='accepting_submissions',
            new_name='accepting_show_submissions',
        ),
        migrations.AddField(
            model_name='event',
            name='accepting_staff_applications',
            field=models.BooleanField(default=False, help_text='Accepting applications for staff'),
        ),
    ]
