# Generated by Django 3.2.16 on 2022-10-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0022_auto_20221019_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='week',
        ),
        migrations.AddField(
            model_name='slot',
            name='week',
            field=models.ManyToManyField(to='programming.Week'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='PEN', max_length=10)),
                ('show', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show')),
                ('slot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.slot')),
            ],
        ),
    ]
