# Generated by Django 3.2.16 on 2022-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0024_week_has_performances'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='slot_preference',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='slot',
            constraint=models.UniqueConstraint(fields=('show', 'slot_preference'), name='unique_slot_preference'),
        ),
    ]
