# Generated by Django 3.2.16 on 2022-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0025_auto_20221021_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='title',
            field=models.CharField(choices=[('W0', 'Week 0 Start'), ('W1', 'Week 1 Start'), ('W2', 'Week 2 Start'), ('W3', 'Week 3 Start'), ('W4', 'Week 4 Start')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='week',
            constraint=models.UniqueConstraint(fields=('title', 'event'), name='unique_weeks_in_event'),
        ),
    ]
