# Generated by Django 3.2.16 on 2022-10-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20221021_0145'),
        ('programming', '0027_alter_slot_has_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='lead_contact',
            field=models.ForeignKey(limit_choices_to='person_type==COMPY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contact', to='people.person'),
        ),
    ]
