# Generated by Django 3.2.16 on 2022-10-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20221021_0145'),
        ('programming', '0031_alter_company_company_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('invoice_status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to recipient'), ('PAID', 'Paid by recipient')], default='DRAFT', max_length=20)),
                ('invoice_date', models.DateField(null=True)),
                ('xero_reference', models.CharField(blank=True, max_length=50)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.company')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programming.show')),
            ],
        ),
    ]
