# Generated by Django 3.2.16 on 2022-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20221024_1932'),
        ('programming', '0032_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='lead_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='show_lead_contact', to='people.person'),
        ),
    ]
