# Generated by Django 3.2.16 on 2022-10-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0033_alter_show_lead_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('DRA', 'Draft'), ('APP', 'Applictation Submitted'), ('COM', 'Complete')], default='APP', help_text='Application status', max_length=30),
        ),
    ]
