# Generated by Django 3.2.16 on 2022-10-28 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0036_auto_20221028_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['year']},
        ),
    ]
