# Generated by Django 3.2.16 on 2022-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0037_alter_event_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('DRA', 'Draft'), ('APP', 'Application Submitted'), ('COM', 'Complete')], default='DRA', help_text='Application status', max_length=30),
        ),
    ]
