# Generated by Django 3.2.16 on 2022-10-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0038_alter_show_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': [('dir_can_make_offer', 'Can make offer')]},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'permissions': [('dir_can_administrate_shows', 'Can be administrator of a show')]},
        ),
    ]
