# Generated by Django 3.2.16 on 2022-10-29 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0040_alter_show_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='programming.company'),
        ),
    ]
