# Generated by Django 3.2.16 on 2022-10-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0041_alter_show_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='status',
            field=models.CharField(choices=[('DRA', 'Draft'), ('APP', 'Application Submitted (waiting for an offer)'), ('COM', 'Complete')], default='DRA', help_text='Application status', max_length=30),
        ),
    ]
