# Generated by Django 3.2.16 on 2022-10-17 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programming', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ManyToManyField(to='programming.Company'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.contactdetails'),
        ),
        migrations.AddField(
            model_name='person',
            name='site_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
