# Generated by Django 3.2.16 on 2022-10-17 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_site_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.contactdetails'),
        ),
    ]
