# Generated by Django 3.2.16 on 2022-10-17 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_alter_person_site_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='site_user',
        ),
    ]
