# Generated by Django 3.2.16 on 2022-10-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_remove_person_site_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactDetails',
            new_name='ContactDetail',
        ),
    ]
