# Generated by Django 3.2.16 on 2022-10-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_rename_contactdetails_contactdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_company',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
