# Generated by Django 3.2.16 on 2022-10-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_person_site_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('STAFF', 'Paradise Green Staff'), ('COMPY', 'Performing Company Member'), ('EMGCY', 'Staff Emergency Contact')], default='COMPY', max_length=30),
        ),
    ]
