# Generated by Django 3.2.16 on 2022-10-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20221019_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact_details',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
    ]
