# Generated by Django 3.2.16 on 2022-10-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20221019_0043'),
    ]

    operations = [
    ]
