# Generated by Django 3.2.16 on 2022-10-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0032_invoice'),
        ('people', '0016_auto_20221021_0145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='company',
        ),
        migrations.CreateModel(
            name='PersonShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DIR', 'Director'), ('PRO', 'Producer'), ('ACT', 'Performer'), ('STG', 'Stage Manager'), ('TCH', 'Technician'), ('OTH', 'Other')], default='ACT', max_length=30)),
                ('role_other', models.CharField(blank=True, max_length=30)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.show')),
            ],
        ),
    ]
