# Generated by Django 3.2.16 on 2022-10-27 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20221024_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personshow',
            options={'verbose_name': 'Person - Show Relationship', 'verbose_name_plural': 'Person - Show Relationships'},
        ),
        migrations.AlterField(
            model_name='personshow',
            name='person',
            field=models.ForeignKey(limit_choices_to={'person_type': 'COMPY'}, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='personshow',
            name='role_other',
            field=models.CharField(blank=True, max_length=30, verbose_name='Other:'),
        ),
    ]
