# Generated by Django 3.2.16 on 2022-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20221028_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_director',
            field=models.BooleanField(default=False),
        ),
    ]
