# Generated by Django 3.2.16 on 2022-10-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programming', '0018_event_accepting_submissions'),
        ('people', '0013_auto_20221018_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(blank=True, help_text='A role offered on the staff, eg. Technician', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_bio', models.TextField()),
                ('event_application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.event')),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('roles_declined', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_declined', to='staffing.staffrole')),
                ('roles_desired', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_desired', to='staffing.staffrole')),
                ('roles_willing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_willing', to='staffing.staffrole')),
                ('weeks_available', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programming.week')),
            ],
        ),
    ]
