# Generated by Django 3.2.16 on 2022-10-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0020_auto_20221019_0033'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='weeks_available',
        ),
        migrations.AddField(
            model_name='application',
            name='weeks_available',
            field=models.ManyToManyField(to='programming.Week'),
        ),
    ]
