# Generated by Django 3.2.16 on 2022-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0002_auto_20221019_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='roles_declined',
        ),
        migrations.AddField(
            model_name='application',
            name='roles_declined',
            field=models.ManyToManyField(related_name='roles_declined', to='staffing.StaffRole'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='roles_desired',
        ),
        migrations.AddField(
            model_name='application',
            name='roles_desired',
            field=models.ManyToManyField(related_name='roles_desired', to='staffing.StaffRole'),
        ),
        migrations.RemoveField(
            model_name='application',
            name='roles_willing',
        ),
        migrations.AddField(
            model_name='application',
            name='roles_willing',
            field=models.ManyToManyField(related_name='roles_willing', to='staffing.StaffRole'),
        ),
    ]
