# Generated by Django 3.2.16 on 2022-10-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0004_alter_staffrole_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='department',
            field=models.CharField(choices=[('H', 'Front of House'), ('K', 'Kitchen'), ('T', 'Technical'), ('A', 'Administration'), ('D', 'Duty')], default='H', max_length=50),
        ),
        migrations.AddField(
            model_name='staffrole',
            name='is_management',
            field=models.BooleanField(default=False),
        ),
    ]
