# Generated by Django 3.2.16 on 2022-10-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0005_auto_20221019_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffrole',
            options={'ordering': ['department', 'role_name']},
        ),
    ]
