# Generated by Django 3.2.16 on 2022-10-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0006_alter_staffrole_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ACC', 'Offer accepted'), ('OFF', 'Offer made'), ('REJ', 'Offer rejected'), ('APP', 'Application complete'), ('INC', 'Application started')], default='INC', max_length=30, verbose_name='Application status'),
        ),
    ]
