# Generated by Django 3.2.16 on 2022-10-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0007_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='How the link appears, eg "Rota"', max_length=100)),
                ('link', models.URLField(blank=True, help_text="The full link to the page, don't forget the https://!")),
                ('ordering', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Quick Link',
                'verbose_name_plural': 'Quick Links',
                'ordering': ['ordering'],
            },
        ),
    ]
