# Generated by Django 3.2.16 on 2022-10-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0038_alter_show_status'),
        ('staffing', '0008_quicklink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Volunteer Application', 'verbose_name_plural': 'Volunteer Applications'},
        ),
        migrations.CreateModel(
            name='WeekPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staffing.application')),
                ('weeks', models.ManyToManyField(to='programming.Week')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
