# Generated by Django 3.2.16 on 2022-10-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0009_auto_20221029_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrole',
            name='appears_in_application',
            field=models.BooleanField(default=True, help_text="Deselect for special roles only appearing on the rota and not selectable in the volunteer application form, eg. 'Other', 'Build Manager', etc."),
        ),
    ]
