# Generated by Django 3.2.16 on 2022-10-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0010_staffrole_appears_in_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='roles_declined',
            field=models.ManyToManyField(blank=True, related_name='roles_declined', to='staffing.StaffRole'),
        ),
        migrations.AlterField(
            model_name='application',
            name='roles_desired',
            field=models.ManyToManyField(blank=True, related_name='roles_desired', to='staffing.StaffRole'),
        ),
        migrations.AlterField(
            model_name='application',
            name='roles_willing',
            field=models.ManyToManyField(blank=True, related_name='roles_willing', to='staffing.StaffRole'),
        ),
    ]
