# Generated by Django 3.2.16 on 2022-10-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0038_alter_show_status'),
        ('people', '0020_remove_person_is_director'),
        ('staffing', '0011_auto_20221029_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('ACC', 'Offer accepted'), ('OFF', 'Offer made'), ('REJ', 'Offer rejected'), ('APP', 'Application complete'), ('INC', 'Application started'), ('WIT', 'Application withdrawn')], default='INC', max_length=30, verbose_name='Application status'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('person', 'event_application')},
        ),
    ]
