# Generated by Django 3.2.16 on 2022-10-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffing', '0012_auto_20221029_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('dir_can_accept_application', 'Can accept applications')], 'verbose_name': 'Volunteer Application', 'verbose_name_plural': 'Volunteer Applications'},
        ),
    ]
