# Generated by Django 3.2.16 on 2022-10-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0042_alter_show_status'),
        ('staffing', '0015_alter_application_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACC', 'Accepted'), ('REJ', 'Rejected')], default='PEN', max_length=10)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staffing.application')),
                ('weeks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programming.week')),
            ],
            options={
                'verbose_name': 'Volunteer Offer',
                'verbose_name_plural': 'Volunteer Offers',
            },
        ),
    ]
