# Generated by Django 3.2.16 on 2022-10-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0042_alter_show_status'),
        ('staffing', '0016_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='weeks',
        ),
        migrations.AddField(
            model_name='offer',
            name='weeks',
            field=models.ManyToManyField(to='programming.Week'),
        ),
    ]
